name: Mi primera Automatizacion


on:
  push:
    branches: [ master ]

jobs:
  saludar:
    runs-on: ubuntu-latest

    steps:
      - name: Paso 1 - Saludar en consola
        run: echo "Hola! Estoy ejecutandome de forma automatica en la nube."

      - name: Paso 2 - Mostrar la fecha actual
        run: date
